title: black ends
description: gunk pop
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
permalink: /:year/:month/:day/:title
future: true
logo: /assets/img/belogo-just-black-ends-white-black-bg.svg
